- name: add grafana gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: add grafana repo 
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install grafana
  apt: 
    name: grafana
    state: present
    update_cache: yes

- name: Create a dricetory for dashboards
  shell: mkdir -p /opt/grafana/dashboards

- name: Copy systemd unit to start grafana-server after restart
  copy:
    src: config/grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: '0644'
 
- name: Enable grafana-server and run it on host.
  systemd:
    name: grafana-server
    state: started
    enabled: yes


